SELECT * FROM (
    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS AA,PRODUCT_ID AS BB,USER_ID AS CC ,SALES_AMOUNT FROM ONLINE_SALE
        WHERE 1 = 1
            AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'

UNION ALL

    SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') AS AA,PRODUCT_ID AS BB, NULL USER_ID ,SALES_AMOUNT FROM OFFLINE_SALE
        WHERE 1 = 1
            AND TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-03'
) AA 
ORDER BY AA.AA, AA,BB, AA.CC