WITH DIFFER_DATE AS (
                    SELECT AI.ANIMAL_ID, AI.NAME, AO.DATETIME-AI.DATETIME AS DIFFER
                    FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO
                    ON AI.ANIMAL_ID = AO.ANIMAL_ID
                    ORDER BY AO.DATETIME-AI.DATETIME DESC
    )

SELECT ANIMAL_ID, NAME
FROM DIFFER_DATE
FETCH NEXT 2 ROWS ONLY;