SELECT 
    A.WRITER_ID, 
    B.NICKNAME, 
    SUM(A.PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD A,
    USED_GOODS_USER B
WHERE
    A.WRITER_ID = B.USER_ID
    AND A.STATUS = 'DONE'
    -- AND TOTAL_SALES >= 700000
GROUP BY 
    A.WRITER_ID, 
    B.NICKNAME
HAVING
    SUM(A.PRICE) >= 700000
ORDER BY
    TOTAL_SALES