SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
  FROM (
        SELECT CATEGORY, PRICE AS MAX_PRICE
             , RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) RNK, PRODUCT_NAME
          FROM FOOD_PRODUCT
         WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
         ORDER BY RNK ASC FETCH FIRST 1 ROW WITH TIES
      )
 ORDER BY MAX_PRICE DESC