SELECT  A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM    BOOK A, AUTHOR B,
(SELECT  BOOK_ID, TO_CHAR(SALES_DATE, 'YYYYMMDD'), SALES
FROM    BOOK_SALES
WHERE   TO_CHAR(SALES_DATE, 'YYYYMMDD') BETWEEN '20220101' AND '20220131') C
WHERE   A.BOOK_ID = C.BOOK_ID
  AND   A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY 1, 3 DESC