SELECT B.TITLE AS TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_REPLY R LEFT OUTER JOIN USED_GOODS_BOARD B
ON R.BOARD_ID = B.BOARD_ID
WHERE B.CREATED_DATE > TO_DATE('20220930', 'YYYY-MM-DD') AND B.CREATED_DATE < TO_DATE('20221101','YYYY-MM-DD') 
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;