SELECT DISTINCT CC.CAR_ID
FROM 
(   
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE='세단'
) CC
INNER JOIN
CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
ON CC.CAR_ID = RH.CAR_ID
WHERE TO_CHAR(RH.START_DATE,'MM')='10'
ORDER BY CC.CAR_ID DESC;